name: CI

on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{  github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --targets=lint
      - run: npx prettier --check .

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
      actions: "read"
      pull-requests: write
    steps:
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check User Permission
        if: steps.checkAccess.outputs.require-result == 'false'
        run: |
          echo "${{ github.triggering_actor }} does not have permissions on this repo."
          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
          echo "Job originally triggered by ${{ github.actor }}"
          exit 1

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{  github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_DEFAULT_ROLE }}
          role-session-name: GithubActions

      - uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - name: Build
        run: npx nx affected --target=build --parallel=3
      - name: Test
        run: npx nx affected --target=test --parallel=3 --ci --code-coverage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VERTEXAI_LOCATION: ${{ secrets.VERTEXAI_LOCATION }}
          VERTEXAI_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
